version: "3.7"

volumes:
  postgres_data:


services:
  db:
    container_name: postgres_db
    image: postgres:13.15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gh_slaking_springai
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 20s
      retries: 5
