version: "3.5"

services:

  postgres:
    container_name: postgres
    image: postgres:13.13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=slakingspringbed
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db

volumes:
  postgres_data:
